### ISSUE TITLE
AttributeError: 'EasyDict' object has no attribute 'TAG'

### ISSUE THREAD

**Issue by onlyonewater** [microsoft/2D-TAN#45]
Hi, songyang, when I want to run Multi-scale 2d-tan, the command is as follows: `python moment_localization/run.py --cfg experiments/charades/MS-2D-TAN-G-VGG.yaml --verbose`, but an error occurs: `AttributeError: 'EasyDict' object has no attribute 'TAG'`, so, what's wrong??

**Comment by onlyonewater** [comment]
when run the above command ,there may be another bug, `FileNotFoundError: [Errno 2] No such file or directory: 'data/Charades/Charades_v1_train.csv'`, I think the `DATA-DIR` in config file may be "data/Charades-STA".

**Comment by onlyonewater** [comment]
and I also want to know, how many device did you used in your experiment?

**Comment by Sy-Zhang** [comment]
> Hi, songyang, when I want to run Multi-scale 2d-tan, the command is as follows: `python moment_localization/run.py --cfg experiments/charades/MS-2D-TAN-G-VGG.yaml --verbose`, but an error occurs: `AttributeError: 'EasyDict' object has no attribute 'TAG'`, so, what's wrong??

I have fixed the bug now.

**Comment by onlyonewater** [comment]
OK, thanks, but I have a question, when I use 4*2080TI, the error occurs: `RuntimeError: CUDA out of memory. Tried to allocate 290.00 MiB (GPU 0; 10.76 GiB total capacity; 9.68 GiB already allocated; 8.44 MiB free; 9.97 GiB reserved in total by PyTorch)`, so, how many device did you used in your experiment?

**Comment by Sy-Zhang** [comment]
> when run the above command ,there may be another bug, `FileNotFoundError: [Errno 2] No such file or directory: 'data/Charades/Charades_v1_train.csv'`, I think the `DATA-DIR` in config file may be "data/Charades-STA".

Thanks for noticing. I have changed the repo's name to keep it consistent with the master branch.

**Comment by Sy-Zhang** [comment]
> OK, thanks, but I have a question, when I use 4*2080TI, the error occurs: `RuntimeError: CUDA out of memory. Tried to allocate 290.00 MiB (GPU 0; 10.76 GiB total capacity; 9.68 GiB already allocated; 8.44 MiB free; 9.97 GiB reserved in total by PyTorch)`, so, how many device did you used in your experiment?

I use v100x8 for training. Decreasing batch size should get similar performance.

**Comment by onlyonewater** [comment]
I don't know what went wrong, when I use 8*2080Ti, the error still occurs: `RuntimeError: CUDA out of memory. Tried to allocate 290.00 MiB (GPU 0; 10.76 GiB total capacity; 9.68 GiB already allocated; 14.44 MiB free; 9.97 GiB reserved in total by PyTorch)`, and the batch size is 16, and when the batch size is 8, there is another error occurs: `raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))`, so what's wrong? I think the model is too large?

**Comment by onlyonewater** [comment]
Hi, songyang, I want to know whether the file `charades_i3d_rgb_25fps.hdf5` (url: https://rochester.app.box.com/s/swu6rlqcdlebvwml8dyescmi7ra0owc5/folder/137190128478)is a fine-tuning feature on Charades? or not?

**Comment by Sy-Zhang** [comment]
> 

This is not a finetuned version.

**Comment by Sy-Zhang** [comment]
> > 
> 
> This is not a finetuned version.



> Hi, songyang, I want to know whether the file `charades_i3d_rgb_25fps.hdf5` (url: https://rochester.app.box.com/s/swu6rlqcdlebvwml8dyescmi7ra0owc5/folder/137190128478) is a fine-tuned feature on Charades? or not?

This is not a finetuned version.

**Comment by onlyonewater** [comment]
OK, I get it, thanks!!!
